spring.application.name=karateaicoach

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=KarateAI

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/

spring.ai.openai.api-key=${OPEN_AI_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
